version: '3'
x-log-config: &log-config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "5"
volumes:
  lws:
services:
  # lws-web:
  #     container_name: lws-web
  #     build:
  #       context: lws-web
  #       dockerfile: Dockerfile
  #     restart: unless-stopped
  #     depends_on:
  #       - monero-lws
  #     environment:
  #         NUXT_LWS_API_KEY: ayoo
  #         NUXT_LWS_ADMIN_URL: http://127.0.0.1:8080
  #     ports:
  #       - 127.0.0.1:5000:5000
  #     <<: *log-config
  redis:
    image: redis:latest
    container_name: monero-lws-cache
    restart: always
    ports:
      - 127.0.0.1:6379:6379
  monero-lws:
    container_name: monero-lws
    build:
      context: monero-lws
      dockerfile: Dockerfile
      args:
        MONERO_BRANCH: release-v0.18
        MONERO_COMMIT_HASH: 2f45d5c615492dffa456489d73543870e5a224ab
        NPROC: 4
    restart: unless-stopped
    depends_on:
      - monerod
    ports:
      - 127.0.0.1:8081:8081
      - 127.0.0.1:8080:8080
    volumes:
      - lws:/home/monero-lws/.bitmonero/light_wallet_server
    command:
      --scan-threads 4 --rest-threads 4 --rest-server http://0.0.0.0:8080 --admin-rest-server http://0.0.0.0:8081 --log-level 1 --daemon=tcp://monerod:18082 --sub=tcp://monerod:18083 --confirm-external-bind
    <<: *log-config
  monerod:
    container_name: monerod
    build:
      context: docker-monero-node/dockerfiles
      dockerfile: monero_nocompile
    restart: unless-stopped
    volumes:
      - ~/.bitmonero:/srv/monerod
    command:
      monerod --data-dir /srv/monerod/ --p2p-bind-ip=0.0.0.0 --p2p-bind-port=18080 --rpc-bind-ip=0.0.0.0 --rpc-bind-port=18081 --zmq-rpc-bind-ip=0.0.0.0 --zmq-rpc-bind-port=18082 --zmq-pub tcp://0.0.0.0:18083 --rpc-restricted-bind-ip=0.0.0.0 --rpc-restricted-bind-port=18089 --non-interactive --confirm-external-bind --public-node
    <<: *log-config
