version: '3'
x-log-config: &log-config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "5"
volumes:
  lws:
  mymonero:
  lwsadmin:
services:
  lwsadmin:
    container_name: lwsadmin
    image: lalanza808/lwsadmin
    restart: unless-stopped
    depends_on:
      - monero-lws
    environment:
        LWS_URL: http://monero-lws:8080
        LWS_ADMIN_URL: http://monero-lws:8081
        QUART_ENV: production
        HOST: 0.0.0.0
        DEBUG: 0
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - lwsadmin:/srv/lwsadmin
    user: "1000:1000"
    command:
      ./.venv/bin/poetry run start
    <<: *log-config
  mymonero-web:
    container_name: mymonero-web
    image: lalanza808/mymonero-web
    environment:
      MYMONERO_WEB_NETTYPE: 0
      MYMONERO_WEB_SERVER_URL: ${DOMAIN}${PATH}
      MYMONERO_WEB_APP_NAME: LZAXMR
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - mymonero:/app
    <<: *log-config
  monero-lws:
    container_name: monero-lws
    image: lalanza808/lws
    restart: unless-stopped
    network_mode: host
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - lws:/home/monero-lws/.bitmonero/light_wallet_server
    command:
      --scan-threads 4 --rest-threads 4 --rest-server http://127.0.0.1:8080/lws --admin-rest-server http://127.0.0.1:8081 --log-level 1 --daemon=tcp://127.0.0.1:18082 --sub=tcp://127.0.0.1:18083 --access-control-origin "${DOMAIN}"
    <<: *log-config